version: "3.8"
# https://github.com/ruanbekker/grafana-tempo-loki-tracing/blob/main/payment_service/app.py
x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "1m"
    max-file: "1"
    tag: "{{.Name}}"

services:
  client-service:
    build: ./client-service
    volumes:
      - ./client-service:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
      # Add environment variables for Loki and Tempo if needed
    depends_on:
      - grafana
      - tempo
      - loki
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    logging: *default-logging

  invoice-service:
    build: ./invoice-service
    volumes:
      - ./invoice-service:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=development
      # Add environment variables for Loki and Tempo if needed
    depends_on:
      - grafana
      - tempo
      - loki
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
    logging: *default-logging

  promtail:
    image: grafana/promtail:2.9.2
    container_name: promtail
    volumes:
      - ./config/promtail/promtail.yaml:/etc/promtail/docker-config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/docker-config.yaml
    depends_on:
      - loki
    networks:
      - traces
    logging: *default-logging

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - loki
      - tempo
    volumes:
      - ./config/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/provisioning-datasources.yaml:ro
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"
      # GF_INSTALL_PLUGINS: "grafana-tempo-app,grafana-loki-datasource"
    networks:
      - traces
    logging: *default-logging

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - traces
    logging: *default-logging

  prometheus:
    image: prom/prometheus:v2.48.0
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./config/prometheus/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"
    networks:
      - traces
    logging: *default-logging

  tempo:
    image: grafana/tempo:2.3.1
    container_name: tempo
    ports:
      - 3200:3200 # tempo http
      - 9095:9095 # tempo grpc
      - 14268:14268 # jaeger ingest
      - 4318:4318 # otlp http
      - 4317:4317 # otlp grpc
    volumes:
      - ./config/tempo/tempo-local.yaml:/etc/tempo-local.yaml
    command: ["-config.file=/etc/tempo-local.yaml"]
    networks:
      - traces
    logging: *default-logging

volumes:
  tempo-data:
  loki-data:

networks:
  traces:
    name: traces
    driver: bridge
